server:
  host: "0.0.0.0"
  port: 8443
  workers: 4
  max_connections: 10000
  tls:
    enabled: true
    cert_path: "certs/cert.pem"
    key_path: "certs/key.pem"
    acme:
      enabled: false  # 默认使用自签证书，生产环境可启用
      domains:
        - "proxy.example.com"
      email: "admin@example.com"
      directory_url: "https://acme-staging-v02.api.letsencrypt.org/directory"

gemini:
  base_url: "https://generativelanguage.googleapis.com"
  timeout_seconds: 30
  api_keys:
    - id: "key1"
      key: "AIzaSyXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" # Replace with your actual key
      weight: 100
      max_requests_per_minute: 60
    - id: "key2"
      key: "AIzaSyYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY" # Replace with your actual key
      weight: 100
      max_requests_per_minute: 60

auth:
  enabled: true
  jwt_secret: "your-super-secret-key-that-is-long-and-secure"
  rate_limit_per_minute: 100

metrics:
  enabled: true
  prometheus_port: 9443  # HTTPS 端口
  tls:
    enabled: true
    cert_path: "certs/api-cert.pem"
    key_path: "certs/api-key.pem"